Fix device flow authorization endpoint
CZ-NIC/pyoidc pull request #884
Opened 2024-11-06 03:58 UTC by bacek

Device authorization endpoint is `device_authorization_endpoint` as per https://www.rfc-editor.org/rfc/rfc8628.html#section-4

- [ ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.
- [ ] New code is annotated.
- [ ] Changes are covered by tests.
---

2024-11-11 07:48 UTC, tpazderka requested changes

2024-11-11 07:48 UTC, tpazderka commented on src/oic/extension/device_flow.py
> +            self.host.provider_info["device_authorization_endpoint"], "POST", req.to_urlencoded()
Could you please update the formatting as suggested by the formater?

Running `black src/ tests/` should be sufficient.

2025-04-22 06:40 UTC, bacek commented on src/oic/extension/device_flow.py
> +            self.host.provider_info["device_authorization_endpoint"], "POST", req.to_urlencoded()
> Could you please update the formatting as suggested by the formater?
> 
> Running `black src/ tests/` should be sufficient.

Sorry, totally missed it.

I run `black` on src. Running on `tests` brings too many unrelated changes.

2025-04-22 11:02 UTC, tpazderka commented on src/oic/extension/device_flow.py
> +            self.host.provider_info["device_authorization_endpoint"], "POST", req.to_urlencoded()
Yeah, sorry... we switched to ruff in the meantime...

2025-04-23 00:22 UTC, bacek commented on src/oic/extension/device_flow.py
> +            self.host.provider_info["device_authorization_endpoint"], "POST", req.to_urlencoded()
No worries. Updated with ruff.

2025-04-23 11:11 UTC, tpazderka approved these changes

2025-04-23 11:51 UTC, merged